<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '0a9c38cbf7473ee599cad015d25f3dce',
  'DATABASE_URL' => 'postgresql://ok:ok@localhost:5432/test',
);


# https://habr.com/ru/post/460345/